[tool.poetry]
name = "hackerrank"
version = "0.1.0"
description = ""
authors = ["Gustavo Garcia"]

[tool.poetry.dependencies]
python = "^3.8"
pytest = "^5.4.3"
ipython = "^7.16.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
